### ISSUE TITLE
model predict error

### ISSUE THREAD

**Issue by RyanYip-Kat** [leefsir/triplet_extraction#5]
When I run model_predict.py as described in readme ,I  got the error:
Traceback (most recent call last):
  File "model_predict.py", line 17, in <module>
    print(model.predict(text))
  File "/home/jovyan/work/triplet_extraction/train/entity_relation_extract.py", line 176, in predict
    ) for s, p, o in spoes
  File "/home/jovyan/work/triplet_extraction/train/entity_relation_extract.py", line 176, in <listcomp>
    ) for s, p, o in spoes
KeyError: 11

And how can I fix it?Thanks!

**Comment by leefsir** [comment]
In this position，When you run predict,&nbsp; &nbsp;self.i2p_dict keys will become str, but the 'p' types is int. You need transition it's types to str


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leefsir/triplet_extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 上午8:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[leefsir/triplet_extraction] model predict error (#5)





 
When I run model_predict.py as described in readme ,I  got the error:
 Traceback (most recent call last):
 File "model_predict.py", line 17, in 
 print(model.predict(text))
 File "/home/jovyan/work/triplet_extraction/train/entity_relation_extract.py", line 176, in predict
 ) for s, p, o in spoes
 File "/home/jovyan/work/triplet_extraction/train/entity_relation_extract.py", line 176, in 
 ) for s, p, o in spoes
 KeyError: 11
 
And how can I fix it?Thanks!

**Comment by RyanYip-Kat** [comment]
OK!Thanks!
